loop_enable: True
speed_control: True
initial_lookahead_distance : 0.5
initial_velocity : 1.0
straight_lookahead_dist : 2.0
turning_lookahead_dist : 0.3
straight_vel : 1.0
turning_vel : 0.5
turn_window_min : 2.25
turn_window_max : 2.75
max_x_deviation : 2.5

