loop_enable: True
speed_control: True
pure_pursuit_rate: 20
initial_lookahead_distance : 0.3
initial_velocity : 1.0
straight_lookahead_dist : 1.5
turning_lookahead_dist : 0.4
straight_vel : 1.5
turning_vel : 0.5
turn_window_min : 2.25
turn_window_max : 2.75
max_x_deviation : 2.65

