loop_enable: True
speed_control: True
pure_pursuit_rate: 20
initial_lookahead_distance : 0.5
initial_velocity : 1.0
straight_lookahead_dist : 1.5
turning_lookahead_dist : 0.65
interpolation_mode : 'quadratic'
kp_quad : 0.75
quad_factor : 2.5
straight_vel : 2.0
turning_vel : 0.5
turn_window_min : 2.0
turn_window_max : 2.5
max_x_deviation : 3.65


